apiVersion: v1
kind: Service
metadata:
  name: my-service
spec:
  type: LoadBalancer
  loadBalancerIP: 35.194.18.4
  selector:
    app: my-app
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80